config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'users/registrations' }
  root 'subjects#index'

  resources :subjects, only: %i[index show] do
    resources :articles, only: %i[show], shallow: true
  end

  get '/public_articles', to: 'articles#index', as: 'public_articles'

  namespace :teacher do
    get '/', to: 'teachers#show', as: ''
    get '/public_articles', to: 'articles#index', as: 'public_articles'

    resources :subjects do
      resources :articles, shallow: true, except: :index

      get '/new-test', to: 'tests#new', as: 'tests_new'
    end

    resources :tests, except: %i[new index] do
      resources :questions, shallow: true do
        resources :answers, only: :create
      end
    end

    delete 'questions/:id/destroy_answers', to: 'questions#destroy_answers', as: 'question_destroy_answers'

    resources :groups
    resources :visibilities, only: %i[create destroy]

    post '/group/:id/add-student/:student_id', to: 'groups#add_to_group', as: 'add_to_group'
    post '/group/:id/kick-student/:student_id', to: 'groups#kick_from_group', as: 'kick_from_group'
  end

  get '/tests/:id', to: 'tests#test_passing', as: 'test_passing'
  post '/tests/:id/start', to: 'tests#start', as: 'start_test'

  resources :test_passages, only: %i[show update] do
    member do
      get :result
    end
  end
end

app/models/article.rb
# frozen_string_literal: true

class Article < ApplicationRecord
  belongs_to :author, class_name: 'Teacher'
  belongs_to :subject

  has_one :test, as: :testable, dependent: :destroy
  has_rich_text :body
  has_many_attached :files

  validates :title, :body, presence: true

  before_destroy :destroy_attached_files

  scope :are_public, -> { where(type: 'Public') }

  self.inheritance_column = :_type_disabled

  private

  def destroy_attached_files
    files.each(&:purge)
  end
end

app/controllers/articles_controller.rb
# frozen_string_literal: true

class ArticlesController < ApplicationController
  before_action :authenticate_user!
  before_action :find_article, only: :show

  def index
    @articles = Article.where(type: 'Public')
  end

  def show; end

  private

  def find_article
    @article = Article.find(params[:id])
  end
end

app/controllers/teacher/articles_controller.rb
# frozen_string_literal: true
class Teacher::ArticlesController < Teacher::BaseController
  before_action :find_article, only: %i[show edit update destroy start]
  before_action :find_subject, only: %i[new create]

  def index
    @articles = Article.where(type: 'Public')
  end

  def new
    @article = @subject.articles.new
  end

  def create
    @article = @subject.articles.new(article_params.merge(author: current_user))

    if @article.save
      flash[:success] = 'Your Article successfully created.'
      redirect_to teacher_article_path(@article)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def update
    if @article.update(article_params)
      flash[:success] = 'Article was updated!'
      redirect_to teacher_article_path(@article)
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @article.destroy
    flash[:success] = 'Article was destroyed!'
    redirect_to teacher_subject_path(@article.subject)
  end

  def show
    if @article.test.present?
      @test = @article.test
    else
      @test = Test.new(author: current_user, testable: @article)
      @questions = @test.questions.build
      @answers = @questions.answers.build
    end
  end

  def edit; end

  private

  def article_params
    params.require(:article).permit(:title, :body, :type, :description, files: [])
  end

  def find_article
    @article = Article.with_attached_files.find(params[:id])
  end

  def find_subject
    @subject = Subject.find(params[:subject_id])
  end
end

app/helpers/articles_helper.rb
# frozen_string_literal: true

module ArticlesHelper
end

app/views/articles/_article.html.slim
.card.mb-4
  h5.card-header =article.subject.title
  .card-body
    h5.card-title
      =article.title
    p.card-subtitle
      =article.description
    small.card-text.text-muted
      ="By #{article.author.name} #{article.author.last_name}"
  .card-footer
    =link_to 'Read', article_path(article), class: 'btn btn-secondary'

app/views/articles/_article_fields.html.slim
.mb-3.row
  .col-sm-2.col-form-label
    =f.label :title, 'Title of article'
  .col-sm-10.col-form-label
    =f.text_field :title, placeholder: 'Title', class: 'form-control'

.mb-3.row
  .col-sm-2.col-form-label
    =f.label :body, 'Enter text'
  .col-sm-10.col-form-label
    =f.text_area :body, class: 'form-control'

app/views/articles/_form.html.slim
=form_with model: @article, local: true do |f|
  =render 'article_fields', f: f

  =f.submit 'Submit', class: 'btn btn-outline-primary btn-md mb-4'

app/views/articles/index.html.slim
.fs-2.mb-3
  =link_to 'Your subjects', subjects_path, class: 'link'
  = " | Public articles"

.card-columns
  =render @articles

app/views/articles/show.html.slim
.fs-2.mb-4.d-inline-block
  .d-inline-block.me-2
    =link_to :back, class: 'icon-back', data_toggle: "tooltip", title: "Back" do
      i class="bi bi-arrow-left"
  .p-0.d-inline-block.me-4
    =@article.title

.mb-1.fs-4
  =sanitize @article.body.to_s

#test-passage.mb-5
  -if @article.test.present?
    =form_tag test_passing_path(@article.test), method: :get, remote: true do
      =submit_tag 'Test', class: 'btn btn-success'