config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'users/registrations' }
  root 'subjects#index'

  resources :subjects, only: %i[index show] do
    resources :articles, only: %i[show], shallow: true
  end

  get '/public_articles', to: 'articles#index', as: 'public_articles'

  namespace :teacher do
    get '/', to: 'teachers#show', as: ''
    get '/public_articles', to: 'articles#index', as: 'public_articles'

    resources :subjects do
      resources :articles, shallow: true, except: :index

      get '/new-test', to: 'tests#new', as: 'tests_new'
    end

    resources :tests, except: %i[new index] do
      resources :questions, shallow: true do
        resources :answers, only: :create
      end
    end

    delete 'questions/:id/destroy_answers', to: 'questions#destroy_answers', as: 'question_destroy_answers'

    resources :groups
    resources :visibilities, only: %i[create destroy]

    post '/group/:id/add-student/:student_id', to: 'groups#add_to_group', as: 'add_to_group'
    post '/group/:id/kick-student/:student_id', to: 'groups#kick_from_group', as: 'kick_from_group'
  end

  get '/tests/:id', to: 'tests#test_passing', as: 'test_passing'
  post '/tests/:id/start', to: 'tests#start', as: 'start_test'

  resources :test_passages, only: %i[show update] do
    member do
      get :result
    end
  end
end

app/models/subject.rb
class Subject < ApplicationRecord
  belongs_to :author, class_name: 'Teacher'

  has_many :articles, dependent: :destroy
  has_many :tests, as: :testable, dependent: :destroy

  has_many :visibilities
  has_many :groups, through: :visibilities

  validates :title, presence: true, uniqueness: true

  has_rich_text :description
end

app/models/teacher.rb
# frozen_string_lite  ral: true

class Teacher < User
  has_and_belongs_to_many :controlled_groups, class_name: 'Group',
                                              join_table: 'groups_users',
                                              foreign_key: 'user_id'


  has_many :created_tests, class_name: 'Test', foreign_key: :author_id, dependent: :destroy
  has_many :created_articles, class_name: 'Article', foreign_key: :author_id, dependent: :destroy

  has_many :created_subjects, class_name: 'Subject', foreign_key: :author_id, dependent: :destroy
  has_many :created_groups, class_name: 'Group', foreign_key: :major_teacher_id

  def author_of?(object)
    id == object.author_id
  end
end

app/controllers/subjects_controller.rb
class SubjectsController < ApplicationController
  before_action :authenticate_user!
  def index
    @subjects = case current_user
                when Admin
                  Subject.all
                when Teacher
                  Subject.where(author: current_user)
                else
                  current_user&.group&.visible_subjects || []
                end
  end

  def show
    @subject = Subject.find(params[:id])
  end
end

app/controllers/teacher/answers_controller.rb
class Teacher::AnswersController < Teacher::BaseController
  def create
    @question = Question.find(params[:question_id])

    if params[:answer].instance_of? Array
      params[:answer].each do |attr|
        # With my realisation idk how to deal with unpermitted parameters, so i used this two hacks:
        # https://stackoverflow.com/questions/17335329/activemodelforbiddenattributeserror-when-creating-new-user
        # https://stackoverflow.com/questions/46029084/rails-unable-to-convert-unpermitted-parameters-to-hash
        unlocked_params = ActiveSupport::HashWithIndifferentAccess.new(attr.to_enum.to_h)
        @question.answers.create(unlocked_params)
      end
    else
      @question.answers.create(answer_params)
    end

    redirect_to teacher_question_path(@question)
  end

  private

  def answer_params
    params.require(:answer).permit(:content, :correct)
  end
end

app/controllers/teacher/articles_controller.rb
# frozen_string_literal: true
class Teacher::ArticlesController < Teacher::BaseController
  before_action :find_article, only: %i[show edit update destroy start]
  before_action :find_subject, only: %i[new create]

  def index
    @articles = Article.where(type: 'Public')
  end

  def new
    @article = @subject.articles.new
  end

  def create
    @article = @subject.articles.new(article_params.merge(author: current_user))

    if @article.save
      flash[:success] = 'Your Article successfully created.'
      redirect_to teacher_article_path(@article)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def update
    if @article.update(article_params)
      flash[:success] = 'Article was updated!'
      redirect_to teacher_article_path(@article)
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @article.destroy
    flash[:success] = 'Article was destroyed!'
    redirect_to teacher_subject_path(@article.subject)
  end

  def show
    if @article.test.present?
      @test = @article.test
    else
      @test = Test.new(author: current_user, testable: @article)
      @questions = @test.questions.build
      @answers = @questions.answers.build
    end
  end

  def edit; end

  private

  def article_params
    params.require(:article).permit(:title, :body, :type, :description, files: [])
  end

  def find_article
    @article = Article.with_attached_files.find(params[:id])
  end

  def find_subject
    @subject = Subject.find(params[:subject_id])
  end
end

app/controllers/teacher/base_controller.rb
# frozen_string_literal: true

class Teacher::BaseController < ApplicationController
  layout 'teacher'
  before_action :authenticate_user!
  before_action :teacher_required!

  private

  def teacher_required!
    return if current_user.is_a?(Teacher)

    flash[:danger] = 'You are not required to view this page!'
    redirect_to root_path
  end
end

app/controllers/teacher/groups_controller.rb
class Teacher::GroupsController < Teacher::BaseController
  before_action :find_group, only: %i[destroy add_to_group kick_from_group]

  def index
    @groups = current_user.controlled_groups
    @group = Group.new
  end

  def create
    @group = current_user.created_groups.create(group_params)
    current_user.controlled_groups << @group
  end

  def edit; end

  def update; end

  def show
    @group = Group.includes(:visible_subjects).find(params[:id])
    @visibility = @group.visibilities.new
  end

  def destroy
    return head(:forbidden) unless @group.major_teacher == current_user

    @group.destroy
  end

  def add_to_group
    @student = Student.find(params[:student_id])

    @group.students << @student
  end

  def kick_from_group
    @student = Student.find(params[:student_id])

    @student.update(group_id: nil)
  end

  private

  def group_params
    params.require(:group).permit(:name)
  end

  def find_group
    @group = Group.find(params[:id])
  end
end

app/controllers/teacher/questions_controller.rb
class Teacher::QuestionsController < Teacher::BaseController
  before_action :find_question, only: %i[show destroy update destroy_answers]
  def create
    @question = Test.find(params[:test_id]).questions.create(question_params)
  end

  def show; end

  def destroy
    @question.destroy
    respond_to do |format|
      format.js
      format.html { redirect_to @question.test }
    end
  end

  def destroy_answers
    @question.answers.delete_all
    redirect_to teacher_question_path(@question)
  end

  def update
    @question.update(question_params)
  end

  private

  def question_params
    params.require(:question).permit(:type, :title)
  end

  def find_question
    @question = Question.find(params[:id])
  end
end

app/controllers/teacher/subjects_controller.rb
class Teacher::SubjectsController < Teacher::BaseController
  before_action :find_subject, only: %i[show edit update destroy]
  def index
    @subjects = current_user.created_subjects
  end

  def create
    @subject = current_user.created_subjects.new(subject_params)

    if @subject.save
      flash[:success] = 'New subject created!'
      redirect_to teacher_subject_path(@subject)
    else
      render :new
    end
  end

  def edit; end

  def update
    return head(:forbidden) unless current_user.author_of?(@subject)

    @subject.update(subject_params)

    redirect_to teacher_subject_path(@subject)
  end

  def destroy
    return head(:forbidden) unless current_user.author_of?(@subject)

    @subject.destroy
    flash[:success] = 'Subject was destroyed!'
    redirect_to teacher_subjects_path
  end

  def new
    @subject = Subject.new
  end

  def show; end

  private

  def subject_params
    params.require(:subject).permit(:title, :description)
  end

  def find_subject
    @subject = Subject.find(params[:id])
  end
end

app/controllers/teacher/teachers_controller.rb
class Teacher::TeachersController < Teacher::BaseController
  def show
    # TODO: придумать че сюда запихнуть
    @teacher = current_user
  end
end

app/controllers/teacher/tests_controller.rb
class Teacher::TestsController < Teacher::BaseController
  before_action :find_test, only: %i[destroy edit update]

  def new
    @subject = Subject.find(params[:subject_id])
    @test = @subject.tests.new(author_id: current_user.id)
  end

  def create
    @test = Test.create(test_params)

    respond_to do |format|
      format.js
      format.html { redirect_to teacher_test_path(@test) }
    end
  end

  def destroy
    @test.destroy
    redirect_to teacher_article_path(@test.testable)
  end

  def edit; end

  def update
    @test.update(test_params)
  end

  def show
    @test = Test.includes(:questions).find(params[:id])
    @question = Question.new
  end

  private

  def test_params
    params.require(:test).permit(:title, :author_id, :testable_type, :testable_id, :seconds_for_passage,
                                 questions_attributes: [:title, :type, { answers_attributes: %i[content correct description] }])
  end

  def find_test
    @test = Test.find(params[:id])
  end
end

app/controllers/teacher/visibilities_controller.rb
class Teacher::VisibilitiesController < Teacher::BaseController

  def create
    @visibility = Visibility.new(visibility_params)

    if @visibility.save
      redirect_to teacher_group_path(@visibility.group)
    else
      flash[:alert] = 'Not saved!'
      redirect_to teacher_groups_path
    end
  end

  def destroy
    @visibility = Visibility.find(params[:id])

    redirect_to teacher_group_path(@visibility.destroy.group)
  end

  private

  def visibility_params
    params.require(:visibility).permit(:group_id, :subject_id)
  end
end

app/helpers/subjects_helper.rb
module SubjectsHelper
end

app/helpers/teacher/answers_helper.rb
module Teacher::AnswersHelper
  def answer_form(question)
    case question.type
    when 'MultipleChoice'
      render 'teacher/answers/multiple_choice_form', question: @question
    when 'SingleChoice'
      render 'teacher/answers/single_option_form', question: @question
    else
      render 'teacher/answers/no_choice_form', question: @question
    end
  end
end

app/helpers/teacher/groups_helper.rb
module Teacher::GroupsHelper
end

app/helpers/teacher/questions_helper.rb
module Teacher::QuestionsHelper
  def allowed_types
    [
      ['Multiple choice question', 'MultipleChoice'],
      ['Single choice question', 'SingleChoice'],
      ['No choice question', 'NoChoice']
    ]
  end

  def type(question)
    case question.type
    when 'MultipleChoice'
      'Question with multiple choice'
    when 'SingleChoice'
      'Question with single choice'
    else
      'Question without choice'
    end
  end
end

app/helpers/teacher/subjects_helper.rb
module Teacher::SubjectsHelper
end

app/helpers/teacher/teachers_helper.rb
module Teacher::TeachersHelper
end

app/helpers/teacher/tests_helper.rb
module Teacher::TestsHelper
end

app/helpers/teacher/visibilities_helper.rb
module Teacher::VisibilitiesHelper
  def visibility_for(group, subject)
    Visibility.find_by(group: group, subject: subject)
  end
end

app/views/teacher/subjects/_form.html.slim
=render 'shared/errors', object: subject

=form_with model: [:teacher, subject], local: true do |f|
  =render 'teacher/subjects/subject_fields', f: f

  =f.submit 'Submit', class: 'btn btn-outline-primary btn-md mb-4'

app/views/teacher/subjects/_subject.html.slim
li
  =link_to subject.title, teacher_subject_path(subject), class: 'link-primary'

app/views/teacher/subjects/_subject_fields.html.slim
.field.mb-3.row
  .col-sm-2.col-form-label.fs-4
    =f.label :title, 'Title'
  .col-sm-10.col-form-label
    =f.text_field :title, placeholder: 'Title', class: 'form-control'

.field.mb-3
  .fs-4
    =f.label :description, class: 'col-form-label'
  .fs-6
    =f.rich_text_area :description, class: 'form-control'

app/views/teacher/subjects/edit.html.slim
.fs-3
  | Edit subject

=render 'teacher/subjects/form', subject: @subject

app/views/teacher/subjects/index.html.slim
.fs-2.mb-4.d-inline-block
  .p-0.d-inline-block.me-4
    | Subjects
  .d-inline-block.me-3
    =link_to new_teacher_subject_path, class: 'icon-new', data_toggle: "tooltip", title: "New" do
      i class="bi bi-plus-square"

ul.fs-4
  =render @subjects

app/views/teacher/subjects/new.html.slim
.fs-2.mb-4
  | New Subject

=render 'teacher/subjects/form', subject: @subject

app/views/teacher/subjects/show.html.slim
.fs-2.mb-4.d-inline-block
  .d-inline-block.me-2
    =link_to :back, class: 'icon-back', data_toggle: "tooltip", title: "Back" do
      i class="bi bi-arrow-left"
  .p-0.d-inline-block.me-4
    =@subject.title
  -if current_user.author_of?(@subject)
    .d-inline-block.me-3
      =link_to edit_teacher_subject_path(@subject), class: 'icon-edit', data_toggle: "tooltip", title: "Edit" do
        i class="bi bi-pencil-square"
    .d-inline-block
      = link_to teacher_subject_path(@subject), class: 'icon-delete', data: { method: :delete, confirm: 'Are you sure?' },
              data_toggle: "tooltip", title: "Delete" do
        i class="bi bi-trash"

#accordionPanelsStayOpenExample.accordion
  .accordion-item
    h2#panelsStayOpen-headingOne.accordion-header
      button.accordion-button aria-controls="panelsStayOpen-collapseOne" aria-expanded="true" data-bs-target="#panelsStayOpen-collapseOne" data-bs-toggle="collapse" type="button"
        .fs-4
          strong Description
    #panelsStayOpen-collapseOne.accordion-collapse.collapse.show aria-labelledby="panelsStayOpen-headingOne"
      .accordion-body.fs-4
        =sanitize @subject.description.to_s

  .accordion-item
    h2#panelsStayOpen-headingTwo.accordion-header
      button.accordion-button.collapsed aria-controls="panelsStayOpen-collapseTwo" aria-expanded="false" data-bs-target="#panelsStayOpen-collapseTwo" data-bs-toggle="collapse" type="button"
        .fs-4.d-inline-block
          .p-0.d-inline-block.me-4
            strong Educational materials
          .d-inline-block.me-3
            = link_to new_teacher_subject_article_path(@subject), class: 'icon-new', data_toggle: "tooltip", title: "New" do
              i class="bi bi-plus-square"
    #panelsStayOpen-collapseTwo.accordion-collapse.collapse aria-labelledby="panelsStayOpen-headingTwo"
      .accordion-body.fs-4.p-lg-5
        =render @subject.articles

  .accordion-item
    h2#panelsStayOpen-headingThree.accordion-header
      button.accordion-button.collapsed aria-controls="panelsStayOpen-collapseThree" aria-expanded="false" data-bs-target="#panelsStayOpen-collapseThree" data-bs-toggle="collapse" type="button"
        .fs-4.d-inline-block
          .p-0.d-inline-block.me-4
            strong Tests
          .d-inline-block.me-3
            = link_to teacher_subject_tests_new_path(@subject), class: 'icon-new', data_toggle: "tooltip", title: "New" do
              i class="bi bi-plus-square"
    #panelsStayOpen-collapseThree.accordion-collapse.collapse aria-labelledby="panelsStayOpen-headingThree"
      .accordion-body.fs-4
        ul
          =render collection: @subject.tests, partial: 'teacher/tests/test_without_questions', as: 'test'