config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'users/registrations' }
  root 'subjects#index'

  resources :subjects, only: %i[index show] do
    resources :articles, only: %i[show], shallow: true
  end

  get '/public_articles', to: 'articles#index', as: 'public_articles'

  namespace :teacher do
    get '/', to: 'teachers#show', as: ''
    get '/public_articles', to: 'articles#index', as: 'public_articles'

    resources :subjects do
      resources :articles, shallow: true, except: :index

      get '/new-test', to: 'tests#new', as: 'tests_new'
    end

    resources :tests, except: %i[new index] do
      resources :questions, shallow: true do
        resources :answers, only: :create
      end
    end

    delete 'questions/:id/destroy_answers', to: 'questions#destroy_answers', as: 'question_destroy_answers'

    resources :groups
    resources :visibilities, only: %i[create destroy]

    post '/group/:id/add-student/:student_id', to: 'groups#add_to_group', as: 'add_to_group'
    post '/group/:id/kick-student/:student_id', to: 'groups#kick_from_group', as: 'kick_from_group'
  end

  get '/tests/:id', to: 'tests#test_passing', as: 'test_passing'
  post '/tests/:id/start', to: 'tests#start', as: 'start_test'

  resources :test_passages, only: %i[show update] do
    member do
      get :result
    end
  end
end

app/views/shared/_errors.html.slim
-if object&.errors.present?
  =content_tag :div, class: 'alert alert-danger' do
    b ="#{object.errors.count} error(s) detected:"
    ul class='mb-0'
      -object.errors.full_messages.each do |msg|
        li =msg

app/views/shared/_flash.html.slim
/ -flash.each do |type, msg|
/   div class="alert #{style(type)}" =msg.html_safe

-flash.each do |type, msg|
  -case type
  -when "success"
    div.alert.alert-success =msg
  -when "notice"
    div.alert.alert-primary =msg
  -when "alert"
    div.alert.alert-danger =msg
  -else
    div.alert.alert-light =msg

app/views/shared/_header.html.slim
.container
  nav class="d-flex flex-wrap align-items-center justify-content-center justify-content-lg-start fs-4"
    ul class="nav col-12 col-lg-auto me-lg-auto mb-2 justify-content-center mb-md-0"
      li =link_to 'Online Learning', root_path, class: 'nav-link px-2 text-white'
      -if current_user.is_a?(Teacher)
        li =link_to "Teacher Resources", teacher_path, class: 'nav-link px-2 text-white'

    ul class="nav col-12 col-lg-auto mb-2 mb-md-0"
      - if user_signed_in?
        li class="dropdown"
          = link_to '#', class: 'nav-link px-2 dropdown-toggle text-white', data: { "bs-toggle": 'dropdown' } do
            = current_user.name

          ul class="dropdown-menu"
            li = link_to 'Edit profile', edit_user_registration_path, class: 'dropdown-item'
            li = link_to 'Show profile', root_path, class: 'dropdown-item disabled'

            li
              hr class="dropdown-divider"

            li = link_to 'Log out', destroy_user_session_path, class: 'dropdown-item', data: { method: :delete }
      - else
        li = link_to 'Sign Up', new_user_registration_path, class: 'nav-link px-2 text-white'
        li = link_to 'Log In', new_user_session_path, class: 'nav-link px-2 text-white'

app/views/shared/_teacher_header.html.slim
.container
  nav class="d-flex flex-wrap align-items-center justify-content-center justify-content-lg-start fs-4"
    ul class="nav col-12 col-lg-auto me-lg-auto mb-2 justify-content-center mb-md-0"
      li =link_to 'Online Learning', root_path, class: 'nav-link px-2 text-white'
      li =link_to "Teacher Resources", teacher_path, class: 'nav-link px-2 text-white'

    ul class="nav col-12 col-lg-auto mb-2 mb-md-0"
      li class="dropdown"
        = link_to '#', class: 'nav-link px-2 dropdown-toggle text-white', data: { "bs-toggle": 'dropdown' } do
          = current_user.name

        ul class="dropdown-menu"
          li = link_to 'Edit profile', edit_user_registration_path, class: 'dropdown-item'
          li = link_to 'Show profile', root_path, class: 'dropdown-item disabled'

          li
            hr class="dropdown-divider"

          li = link_to 'Log out', destroy_user_session_path, class: 'dropdown-item', data: { method: :delete }

  nav.fs-5.navbar-expand-lg.border.rounded-3
    .collapse.navbar-collapse#navbarSupportedContent
      ul class="nav col-12 col-lg-auto me-lg-auto mb-2 justify-content-center mb-md-0"
        li.px-5
          = link_to 'Subjects', teacher_subjects_path, class: 'nav-link text-white'
        li.px-5
          = link_to 'Groups', teacher_groups_path, class: 'nav-link text-white'
        li.px-5
          = link_to 'Public articles', teacher_public_articles_path, class: 'nav-link text-white'