config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'users/registrations' }
  root 'subjects#index'

  resources :subjects, only: %i[index show] do
    resources :articles, only: %i[show], shallow: true
  end

  get '/public_articles', to: 'articles#index', as: 'public_articles'

  namespace :teacher do
    get '/', to: 'teachers#show', as: ''
    get '/public_articles', to: 'articles#index', as: 'public_articles'

    resources :subjects do
      resources :articles, shallow: true, except: :index

      get '/new-test', to: 'tests#new', as: 'tests_new'
    end

    resources :tests, except: %i[new index] do
      resources :questions, shallow: true do
        resources :answers, only: :create
      end
    end

    delete 'questions/:id/destroy_answers', to: 'questions#destroy_answers', as: 'question_destroy_answers'

    resources :groups
    resources :visibilities, only: %i[create destroy]

    post '/group/:id/add-student/:student_id', to: 'groups#add_to_group', as: 'add_to_group'
    post '/group/:id/kick-student/:student_id', to: 'groups#kick_from_group', as: 'kick_from_group'
  end

  get '/tests/:id', to: 'tests#test_passing', as: 'test_passing'
  post '/tests/:id/start', to: 'tests#start', as: 'start_test'

  resources :test_passages, only: %i[show update] do
    member do
      get :result
    end
  end
end

app/models/subject.rb
class Subject < ApplicationRecord
  belongs_to :author, class_name: 'Teacher'

  has_many :articles, dependent: :destroy
  has_many :tests, as: :testable, dependent: :destroy

  has_many :visibilities
  has_many :groups, through: :visibilities

  validates :title, presence: true, uniqueness: true

  has_rich_text :description
end

app/controllers/subjects_controller.rb
class SubjectsController < ApplicationController
  before_action :authenticate_user!
  def index
    @subjects = case current_user
                when Admin
                  Subject.all
                when Teacher
                  Subject.where(author: current_user)
                else
                  current_user&.group&.visible_subjects || []
                end
  end

  def show
    @subject = Subject.find(params[:id])
  end
end

app/controllers/teacher/subjects_controller.rb
class Teacher::SubjectsController < Teacher::BaseController
  before_action :find_subject, only: %i[show edit update destroy]
  def index
    @subjects = current_user.created_subjects
  end

  def create
    @subject = current_user.created_subjects.new(subject_params)

    if @subject.save
      flash[:success] = 'New subject created!'
      redirect_to teacher_subject_path(@subject)
    else
      render :new
    end
  end

  def edit; end

  def update
    return head(:forbidden) unless current_user.author_of?(@subject)

    @subject.update(subject_params)

    redirect_to teacher_subject_path(@subject)
  end

  def destroy
    return head(:forbidden) unless current_user.author_of?(@subject)

    @subject.destroy
    flash[:success] = 'Subject was destroyed!'
    redirect_to teacher_subjects_path
  end

  def new
    @subject = Subject.new
  end

  def show; end

  private

  def subject_params
    params.require(:subject).permit(:title, :description)
  end

  def find_subject
    @subject = Subject.find(params[:id])
  end
end

app/helpers/subjects_helper.rb
module SubjectsHelper
end

app/helpers/teacher/subjects_helper.rb
module Teacher::SubjectsHelper
end

app/views/subjects/_subject.html.slim
li =link_to subject.title, subject_path(subject), class: 'link-primary'

app/views/subjects/index.html.slim
.fs-2.mb-3
  = "Your subjects | "
  =link_to 'Public articles', public_articles_path, class: 'link'

.fs-4
  =render @subjects

app/views/subjects/show.html.slim
.fs-2.mb-4.d-inline-block
  .d-inline-block.me-2
    =link_to :back, class: 'icon-back', data_toggle: "tooltip", title: "Back" do
      i class="bi bi-arrow-left"
  .p-0.d-inline-block.me-4
    =@subject.title

#accordionPanelsStayOpenExample.accordion.mb-5
  .accordion-item
    h2#panelsStayOpen-headingOne.accordion-header
      button.accordion-button aria-controls="panelsStayOpen-collapseOne" aria-expanded="true" data-bs-target="#panelsStayOpen-collapseOne" data-bs-toggle="collapse" type="button"
        .fs-5
          strong Description
    #panelsStayOpen-collapseOne.accordion-collapse.collapse.show aria-labelledby="panelsStayOpen-headingOne"
      .accordion-body.fs-5
        =sanitize @subject.description.to_s

  .accordion-item
    h2#panelsStayOpen-headingTwo.accordion-header
      button.accordion-button.collapsed aria-controls="panelsStayOpen-collapseTwo" aria-expanded="false" data-bs-target="#panelsStayOpen-collapseTwo" data-bs-toggle="collapse" type="button"
        .fs-5
          strong Educational materials
    #panelsStayOpen-collapseTwo.accordion-collapse.collapse aria-labelledby="panelsStayOpen-headingTwo"
      .accordion-body.fs-4
        =render @subject.articles

  .accordion-item
    h2#panelsStayOpen-headingThree.accordion-header
      button.accordion-button.collapsed aria-controls="panelsStayOpen-collapseThree" aria-expanded="false" data-bs-target="#panelsStayOpen-collapseThree" data-bs-toggle="collapse" type="button"
        .fs-5
          strong Tests
    #panelsStayOpen-collapseThree.accordion-collapse.collapse aria-labelledby="panelsStayOpen-headingThree"
      .accordion-body.fs-4
        ul
          =render @subject.tests